# Setup
title:               Learn Macaulay2
tagline:             a Software System for Research in Algebraic Geometry
description:         >- # this means to ignore newlines until "url:"
  Macaulay2 is a software system devoted to supporting research in algebraic
  geometry and commutative algebra.
url:                 https://mahrud.github.io
baseurl:             '/LearnM2' # the subpath of your site, e.g. /blog
# gtag:                '' # Google Analytics Tag

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for entries
collections:
  packages:
    output: true
  docs:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  footnote_backlink: "&#x21a9;&#xfe0e;"
  enable_coderay: false
  parse_block_html: true
  math_engine: null # pending https://github.com/github/pages-gem/pull/545

# Exclusions from the final site
exclude:
  - TODO
  - Makefile
  - README.md
  - LICENSE.md
  - proof.gemspec
  - docs

# Theme
remote_theme: "mahrud/proof"
